# Generated by Django 3.2.10 on 2023-07-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jbnu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('belt', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('jurl', models.CharField(max_length=50)),
            ],
        ),
    ]
